# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TmatL <- function(Inspec, Timepoints) {
    .Call(`_MMCoxCL_TmatL`, Inspec, Timepoints)
}

TmatR <- function(Inspec, Timepoints) {
    .Call(`_MMCoxCL_TmatR`, Inspec, Timepoints)
}

TmatLR <- function(Inspec, Timepoints) {
    .Call(`_MMCoxCL_TmatLR`, Inspec, Timepoints)
}

elementwise_pow <- function(A, p) {
    .Call(`_MMCoxCL_elementwise_pow`, A, p)
}

Likelihood_rules <- function(rules, beta, theta, gamma, Data, tL, tR) {
    .Call(`_MMCoxCL_Likelihood_rules`, rules, beta, theta, gamma, Data, tL, tR)
}

WeightFunc <- function(rules, beta, theta, gamma, Data, tL, tR) {
    .Call(`_MMCoxCL_WeightFunc`, rules, beta, theta, gamma, Data, tL, tR)
}

LogLikeliValue <- function(rules, beta, theta, gamma, Data, tL, tR) {
    .Call(`_MMCoxCL_LogLikeliValue`, rules, beta, theta, gamma, Data, tL, tR)
}

TargetLogLikeliValue <- function(par, rules, Data) {
    .Call(`_MMCoxCL_TargetLogLikeliValue`, par, rules, Data)
}

LogLikeliValueInd <- function(rules, beta, theta, gamma, Data, tL, tR) {
    .Call(`_MMCoxCL_LogLikeliValueInd`, rules, beta, theta, gamma, Data, tL, tR)
}

Updateonce <- function(rules, beta, theta, gamma, Data, tL, tR, tLR) {
    .Call(`_MMCoxCL_Updateonce`, rules, beta, theta, gamma, Data, tL, tR, tLR)
}

UpdateonceInd <- function(rules, beta, theta, gamma, Data, tL, tR, tLR) {
    .Call(`_MMCoxCL_UpdateonceInd`, rules, beta, theta, gamma, Data, tL, tR, tLR)
}

MainFuncClosd <- function(Data, rules, Tol) {
    .Call(`_MMCoxCL_MainFuncClosd`, Data, rules, Tol)
}

MainFuncClosdInd <- function(Data, rules, Tol) {
    .Call(`_MMCoxCL_MainFuncClosdInd`, Data, rules, Tol)
}

UpdateonceProfileBeta <- function(Indicator, rules, beta, theta, gamma, Data, tL, tR, tLR) {
    .Call(`_MMCoxCL_UpdateonceProfileBeta`, Indicator, rules, beta, theta, gamma, Data, tL, tR, tLR)
}

UpdateonceProfileBetaInd <- function(Indicator, rules, beta, theta, gamma, Data, tL, tR, tLR) {
    .Call(`_MMCoxCL_UpdateonceProfileBetaInd`, Indicator, rules, beta, theta, gamma, Data, tL, tR, tLR)
}

UpdateonceProfileTheta <- function(rules, beta, theta, gamma, Data, tL, tR, tLR) {
    .Call(`_MMCoxCL_UpdateonceProfileTheta`, rules, beta, theta, gamma, Data, tL, tR, tLR)
}

LogProfileLikeli <- function(Indicator, Data, rules, Tol, beta, theta, gamma) {
    .Call(`_MMCoxCL_LogProfileLikeli`, Indicator, Data, rules, Tol, beta, theta, gamma)
}

LogProfileLikeliInd <- function(Indicator, Data, rules, Tol, beta, theta, gamma) {
    .Call(`_MMCoxCL_LogProfileLikeliInd`, Indicator, Data, rules, Tol, beta, theta, gamma)
}

FindSolution <- function(Indicator, Data, rules, Tol, beta, theta, gamma, Tol2, TheConst, Initial) {
    .Call(`_MMCoxCL_FindSolution`, Indicator, Data, rules, Tol, beta, theta, gamma, Tol2, TheConst, Initial)
}

FindSolutionInd <- function(Indicator, Data, rules, Tol, beta, theta, gamma, Tol2, TheConst, Initial) {
    .Call(`_MMCoxCL_FindSolutionInd`, Indicator, Data, rules, Tol, beta, theta, gamma, Tol2, TheConst, Initial)
}

ComputeCI <- function(Data, rules, Tol, beta, theta, gamma, Tol2, TheConst) {
    .Call(`_MMCoxCL_ComputeCI`, Data, rules, Tol, beta, theta, gamma, Tol2, TheConst)
}

ComputeCIInd <- function(Data, rules, Tol, beta, theta, gamma, Tol2, TheConst) {
    .Call(`_MMCoxCL_ComputeCIInd`, Data, rules, Tol, beta, theta, gamma, Tol2, TheConst)
}

